# Generated by Django 4.2 on 2023-04-12 14:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
        ('categories', '0001_initial'),
        ('ads', '0002_rename_location_user_location_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='location_id',
        ),
        migrations.RemoveField(
            model_name='ad',
            name='author',
        ),
        migrations.AlterField(
            model_name='ad',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='categories.category'),
        ),
        migrations.DeleteModel(
            name='Category',
        ),
        migrations.DeleteModel(
            name='Location',
        ),
        migrations.DeleteModel(
            name='User',
        ),
        migrations.AddField(
            model_name='ad',
            name='author',
            field=models.ManyToManyField(to='users.user'),
        ),
    ]
