# Generated by Django 4.2 on 2023-04-12 14:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
        ('ads', '0003_remove_user_location_id_remove_ad_author_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ad',
            name='author',
        ),
        migrations.AddField(
            model_name='ad',
            name='author',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='users.user'),
        ),
    ]
